// Generated by CoffeeScript 1.4.0
(function() {

  define(function() {
    /*
        This class is responsible for the slide previewing functionality
    */

    var SlideViewer;
    return SlideViewer = (function() {

      SlideViewer.prototype.slideContainer = null;

      SlideViewer.prototype.slideData = null;

      SlideViewer.prototype.baseElement = null;

      SlideViewer.prototype.player = null;

      function SlideViewer(player, $baseElement) {
        this.player = player;
        this.slideContainer = $baseElement.find(".slideContainer");
      }

      SlideViewer.prototype.buildSlidePreview = function() {
        var $li, li, start, videoDuration, _i, _len, _ref, _results;
        videoDuration = this.player.videoA.duration;
        _ref = this.slideContainer.find("li");
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          li = _ref[_i];
          $li = $(li);
          start = $li.data('start');
          $li.css("left", (start / videoDuration * 100) + "%");
          _results.push(this.attachMouseEvents($li));
        }
        return _results;
      };

      SlideViewer.prototype.attachMouseEvents = function($element) {
        var _this = this;
        return $element.on("click", function(event) {
          return _this.player.seek($element.data('start'));
        });
      };

      return SlideViewer;

    })();
  });

}).call(this);
